// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace V_insertVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidV_insertVSIXPackageString = "e3eddf4c-1c6d-40a1-8064-9ae1618dbea3";
        public static Guid guidV_insertVSIXPackage = new Guid(guidV_insertVSIXPackageString);

        public const string guidV_insertVSIXPackageCmdSetString = "8c7b5c3c-0547-4a0c-a9ca-c4f111c6cf29";
        public static Guid guidV_insertVSIXPackageCmdSet = new Guid(guidV_insertVSIXPackageCmdSetString);

        public const string guidImagesString = "dc508f7f-0cab-40a7-9ff4-bab9a299ead4";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TopLevelMenu = 0x1021;
        public const int InsertDateTimeVersionSecondsExcludedCommandId = 0x0105;
        public const int InsertDateTimeVersionSecondsIncludedCommandId = 0x0106;
        public const int bmpPic1 = 0x0001;
    }
}